

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testjpa?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #自动更新|创建表
      ddl-auto: create
    # 日志中显示sql 语句
    show-sql: true
    # 默认创建表的时候，使用  InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 格式化sql语句
    properties:
      hibernate:
        format_sql: true